### PR TITLE
Nazanin

### PR DESCRIPTION
**Pull request by nazi-pira**

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
You need to provide a link to the frontend connected to this API.

**Comment by nazi-pira** [comment]
> You need to provide a link to the frontend connected to this API.

Done :)

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
Your API has CORS issues image

**Comment by nazi-pira** [comment]
fixed the CORS issue

**Review by KarolCislowski — APPROVED** [review]
Great API 🎉

**Pull request closed without merging**
